#!/usr/bin/env python3
"""Compile stars-source.txt (date|sign|text) from the sky lines and per-sign lines below.

The weekly content routine appends new dates to the same structure (see docs/games.md).
Run:  python3 scripts/games-data/stars_build.py   (rewrites stars-source.txt)
"""
from pathlib import Path

SKY = {
    "2026-10-04": "The moon is at its last quarter on a Sunday, a good day to finish what is already half done.",
    "2026-10-05": "A waning crescent and a Monday: the week asks for small, steady starts rather than big ones.",
    "2026-10-06": "The moon thins toward dark. Tuesday suits straightforward conversations and short to-do lists.",
    "2026-10-07": "Midweek under a thin crescent. A good day for tidying, backing up files and clearing small clutter.",
    "2026-10-08": "The old moon is almost gone. Thursday favors finishing one thing properly over starting three.",
    "2026-10-09": "The last sliver of the old moon. Friday is a fair day to rest early and let work wait.",
    "2026-10-10": "New moon today, a natural point to write down what you want from the next month.",
    "2026-10-11": "Still around the new moon, and a Sunday. A quiet day for planning, with nothing urgent in it.",
    "2026-10-12": "The first crescent appears. Monday is a fair day to begin something modest.",
    "2026-10-13": "A waxing crescent on a Tuesday. Ask for what you need in plain words.",
    "2026-10-14": "The crescent grows. Midweek is a good time to check how a plan is actually going.",
    "2026-10-15": "Thursday under a growing crescent. Follow up on a message you left unanswered.",
    "2026-10-16": "A thicker crescent and a Friday. Finish the small tasks that have been nagging you.",
    "2026-10-17": "The moon nears its first quarter. A Saturday for doing something, then resting without guilt.",
}

SIGNS = {
"Aries": [
 "You may want to push through, but the last step will go better if you slow down for it.",
 "Pick the one task you have avoided longest and do ten minutes of it before anything else.",
 "Say the direct thing once, kindly, and then let the other person answer.",
 "A quick call beats a long message today. Keep it short.",
 "Your energy is high by mid-morning. Spend it on the hardest item first.",
 "If something feels unfinished, write down what is left instead of trying to do it all tonight.",
 "Begin a small project you can finish in a week. Choose the first step and do it today.",
 "Someone moves slower than you would like. Let them, and use the time for your own list.",
 "Start early and stop at a sensible hour. A short, focused push will do more than a long one.",
 "Disagreement is easier if you ask a question before you answer. Try it once today.",
 "Pace matters more than speed this week. Check one plan against what has actually happened.",
 "Reply to the message you keep meaning to answer. It will take less time than you expect.",
 "You can clear three small things before lunch. Choose them now and do them in order.",
 "Do something active, then give the rest of the day to something unhurried.",
],
"Taurus": [
 "Stay with the routine that works. A familiar sequence will get you through a long day.",
 "Treat yourself to a proper meal and a break from the screen. Steady habits help.",
 "A plain schedule serves you better than an ambitious one. Keep today simple.",
 "Tidy the place where you work or sleep. A clear surface makes the next day easier.",
 "Finish the thing you started rather than switching to something new. Patience pays off.",
 "Rest is a fine plan for the evening. Cook something you like and keep the phone away.",
 "Write down three things you want to keep doing next month and one you want to drop.",
 "A slow Sunday suits you. Walk somewhere you like and do not check the time.",
 "Start small and in a comfortable place. The first step matters more than the size of it.",
 "Be clear about a limit. Saying it calmly is enough, and you do not need to explain at length.",
 "Check on a habit you began recently. Adjust it if it feels like a chore.",
 "A reliable person in your life would like to hear from you. Send a short note.",
 "Fix one thing around the house that has been bothering you. It is probably a small job.",
 "Spend time outdoors if you can. Slow work in good air suits your pace.",
],
"Gemini": [
 "Ideas come fast. Pick one, write it down in a sentence and leave the rest for later.",
 "Two conversations may overlap. Answer the more urgent one first and be clear about when you will reply to the other.",
 "You will want to learn something new. Keep it to one short article or video.",
 "Clear out an inbox or a folder. Sorting information is more satisfying than it sounds.",
 "Finish one conversation completely before starting another. It will feel lighter.",
 "Talk to someone you have not spoken to for a while. Keep it casual.",
 "Write down what you are curious about this month. Choose one thing to look into.",
 "Read something slowly today instead of skimming. You will notice what you usually miss.",
 "A new contact or idea shows up. Take a note and follow up within the week.",
 "Explain your plan to someone in two sentences. If you cannot, simplify it.",
 "Compare two options on paper rather than in your head. The page will help you choose.",
 "Reply to the question you have been meaning to answer. A short answer is enough.",
 "Switch tasks on purpose rather than by accident. Set a timer and stick to it.",
 "Go somewhere you have not been, even if it is only a different street.",
],
"Cancer": [
 "Finish the day at home if you can. A quiet room will do you good.",
 "Check in with someone close to you. A short message shows you care.",
 "Look after your space first. A small repair or a clean shelf will settle your mind.",
 "A memory may surface. Let it pass without turning it into a task.",
 "Say how you feel in a sentence rather than hinting. People usually respond well to that.",
 "Rest in whatever way is easiest. An early night is a good choice.",
 "Make a list of what you want your home and routines to feel like this month. Keep it short.",
 "A family meal or a call to a relative could be the best part of the day.",
 "Start by making your surroundings comfortable. Then begin the work.",
 "Ask for help with one small thing. You do not have to carry it all.",
 "Check in on a plan that affects other people. They will want to know where it stands.",
 "Return a favor, however small. It will make you feel settled.",
 "Cook for someone, or for yourself. Simple food prepared with attention is enough.",
 "Spend a few hours with people you trust. Leave the rest of the list for tomorrow.",
],
"Leo": [
 "Give someone credit in public. It costs nothing and it will be remembered.",
 "Take the lead on a small task and share the work clearly. People will follow a plain plan.",
 "Do not wait to be asked. Offer your help and be specific about what you can do.",
 "A bit of recognition is due to you. If it does not arrive, state your contribution calmly.",
 "Be generous with your time today, but keep one hour for yourself.",
 "Dress for the day you want. Small effort in how you present yourself helps your mood.",
 "Write down one thing you would like to be known for this month. Make it concrete.",
 "Enjoy a quiet Sunday without performing for anyone. You will recover faster.",
 "Begin something visible, even if it is only a first draft. You can polish it later.",
 "Listen first in a discussion and speak second. Your point will land better.",
 "Check whether the people you lead have what they need. Ask them directly.",
 "Share a piece of good news, however minor. It will lift the mood around you.",
 "Finish a task you can show to others. Seeing it done will give you energy.",
 "Plan something enjoyable for the weekend and invite one other person.",
],
"Virgo": [
 "Check the details one more time, then stop. Perfect is not the target; correct is.",
 "Make a short list and keep it short. Three items done is a good Monday.",
 "Fix a small error you noticed earlier. It will bother you less once it is gone.",
 "Back up what matters and clear what does not. Order will make the rest easier.",
 "Finish and file the last thing on your list. Let it go once it is done.",
 "Do not review it again tonight. The work is good enough to rest on.",
 "Set up the system you will use this month: a folder, a list, a calendar. Keep it simple.",
 "A calm Sunday is a good time to prepare the week. Spend half an hour on it, no more.",
 "Start with the least exciting task, because it will set the tone for the day.",
 "Offer a precise suggestion rather than a general criticism. It will be taken better.",
 "Check what is actually done against what you planned. Adjust the plan, not yourself.",
 "Follow up on the loose end. A short note settles it for good.",
 "Close three small tasks and call it a day. You do not need to do more.",
 "Do some practical errands in the morning and keep the afternoon free.",
],
"Libra": [
 "Choose between two options by lunch. Delay costs more than the difference between them.",
 "Weigh a decision against what you actually want, not what would please everyone.",
 "A fair compromise is possible. Offer it first and keep it specific.",
 "Make your space pleasant to work in. Small touches count.",
 "Decide something small that you have postponed. Enjoy the relief.",
 "Spend the evening with someone whose company is easy.",
 "Write down what balance means for you this month, in work and in rest. Keep it to two lines.",
 "A relaxed Sunday suits you. Plan nothing you do not want to do.",
 "Begin with a conversation instead of a plan. You will see what the plan should be.",
 "Say no politely to one request. It will help you do the others well.",
 "Review a commitment and see whether it still fits. Adjust it if not.",
 "Send the follow-up you drafted. Do not rewrite it again.",
 "Tidy a shared space, and let others know you did it. A small gesture goes far.",
 "Meet a friend or colleague for something simple. A short walk is enough.",
],
"Scorpio": [
 "Keep your own counsel for a bit longer. Not everything needs to be said today.",
 "Focus on one thing that you can see through to the end. Depth beats breadth.",
 "You may notice something others miss. Write it down and wait before acting on it.",
 "Work privately for a few hours. You will get more done than in a meeting.",
 "Let go of a small grievance. It is taking more room than it deserves.",
 "Rest without explaining. Not every quiet evening needs a reason.",
 "Name one thing you want to change this month. Choose a first step you can do alone.",
 "A private day suits you. Read, walk or tidy, and keep it unscheduled.",
 "Begin the hard conversation with a calm sentence. You do not have to say everything at once.",
 "Check whether you are being as open as the situation needs. A little more may help.",
 "Look closely at a plan you trust. One detail may need a second look.",
 "Respond to a message you have been holding back. Keep it brief and honest.",
 "Finish something you began quietly. You may be closer than it seems.",
 "Spend time with one person you trust fully. Skip the crowd.",
],
"Sagittarius": [
 "Look further ahead than today. A short note about next month will help.",
 "Be frank, but check your tone first. You can say the same thing more kindly.",
 "Say yes to something new, as long as it fits in your week.",
 "Plan a small trip or a long walk. Having something to look forward to helps.",
 "Finish the stretch you are on before you look for the next adventure.",
 "A friend's story may be worth your full attention. Put the phone down.",
 "Write down one place or subject you want to explore this month.",
 "Take a long walk without a destination. You will think better afterward.",
 "Start with optimism and keep a plan B written down. Both will help.",
 "Hear the other person out before you argue your point. You may agree more than you think.",
 "Check the details of your travel or schedule for the next two weeks.",
 "Follow up on an invitation you left open. A quick yes or no is kind.",
 "Do the dull thing first, then enjoy the rest of the day guilt free.",
 "Spend the day outdoors if the weather allows. Movement suits you.",
],
"Capricorn": [
 "You do not have to prove anything today. Finish the week's plan and stop.",
 "Set a clear priority for the week and write it where you will see it.",
 "Do the unglamorous task that holds the rest together. It is worth the time.",
 "Delegate one thing that does not need you. Spend the saved time on something that does.",
 "Look at what you got done this week, not only at what remains.",
 "Take an evening off without apologizing. Working harder tomorrow will be easier.",
 "Write down one long-term goal and one step toward it for this month.",
 "A planning hour on Sunday will make the week lighter. Keep it to an hour.",
 "Begin with the task that has a deadline. The rest can be arranged around it.",
 "Be clear about what you can commit to. A smaller promise kept is better than a large one missed.",
 "Review your plan against the calendar. Move one item to make room for what matters.",
 "Send the update you owe to your team or client. A short summary will do.",
 "Finish a task you have been putting off. Then take a proper break.",
 "Spend time with someone outside work. It will help you see your job in proportion.",
],
"Aquarius": [
 "Your own approach may differ from the usual. Explain it in a sentence before you start.",
 "Share an idea with one person you trust before you share it widely.",
 "A different point of view helps. Ask someone who sees the problem another way.",
 "Take a short break from the group and think alone. You may see the answer clearly.",
 "Wrap up a project you have been circling. Done is better than perfect.",
 "Unplug for an evening. Read something that has nothing to do with work.",
 "Write down an idea you want to test this month. Make the test small.",
 "A quiet Sunday gives room for thinking. Keep your phone in another room.",
 "Start a conversation with someone you do not know well. You may learn something useful.",
 "Be honest that you need space, and say when you will be back. People tend to respect that.",
 "Check one of your assumptions. Looking for evidence is more useful than defending it.",
 "Follow up with a person who helped you recently. A thank you is enough.",
 "Join a small group effort if you are asked. You can leave your own mark on it.",
 "Try a new tool or method, but only on something low stakes.",
],
"Pisces": [
 "You may feel other people's moods strongly. Take a few minutes alone to sort out which are yours.",
 "Write down a vague worry as a concrete task. It often gets smaller.",
 "Make time for something creative, even for ten minutes.",
 "Give yourself a quiet hour in the middle of the day. It will steady the rest.",
 "Finish what you can and let go of the rest. Some things will keep until tomorrow.",
 "Rest is productive today. Sleep, a bath or a book are all good choices.",
 "Imagine the month you would like to have. Write three sentences about it.",
 "Spend a calm Sunday near water or trees if you can. It will clear your head.",
 "Start with a gentle plan. A few small steps will carry you further than a big push.",
 "Say what you need without apologizing. A simple request is easier to meet.",
 "Check in with a friend who is going through something. Listening is enough.",
 "Reply to a message from the heart, but keep it short.",
 "Complete one small creative or practical task. It will leave you feeling capable.",
 "Meet someone who makes you feel at ease. Skip anything that feels like a performance.",
],
}

days = sorted(SKY)
lines = ["# date|sign|text  (generated by stars_build.py; sky line + sign line)"]
for i, day in enumerate(days):
    for sign, texts in SIGNS.items():
        assert len(texts) == len(days), (sign, len(texts))
        lines.append(f"{day}|{sign}|{SKY[day]} {texts[i]}")
Path(__file__).with_name("stars-source.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(len(lines) - 1, "readings")
