"""Franchise maps. Each entry: id, display name (current), abbreviation, substrings that identify it in a Wikipedia team label
(including combined labels like 'Philadelphia / San Francisco Warriors'). A relocated or renamed club is one franchise, so
players who shared a locker room count as teammates whatever the city was called."""
NBA = [
 ("ATL", "Atlanta Hawks", ["hawks", "tri-cities"]),
 ("BOS", "Boston Celtics", ["celtics"]),
 ("BKN", "Brooklyn Nets", ["nets"]),
 ("CHA", "Charlotte Hornets", ["bobcats"]),
 ("CHI", "Chicago Bulls", ["bulls"]),
 ("CLE", "Cleveland Cavaliers", ["cavaliers"]),
 ("DAL", "Dallas Mavericks", ["mavericks"]),
 ("DEN", "Denver Nuggets", ["nuggets"]),
 ("DET", "Detroit Pistons", ["pistons"]),
 ("GSW", "Golden State Warriors", ["warriors"]),
 ("HOU", "Houston Rockets", ["rockets"]),
 ("IND", "Indiana Pacers", ["pacers"]),
 ("LAC", "Los Angeles Clippers", ["clippers", "buffalo braves"]),
 ("LAL", "Los Angeles Lakers", ["lakers"]),
 ("MEM", "Memphis Grizzlies", ["grizzlies"]),
 ("MIA", "Miami Heat", ["heat"]),
 ("MIL", "Milwaukee Bucks", ["bucks"]),
 ("MIN", "Minnesota Timberwolves", ["timberwolves"]),
 ("NOP", "New Orleans Pelicans", ["pelicans", "new orleans hornets", "oklahoma city hornets"]),
 ("NYK", "New York Knicks", ["knicks"]),
 ("OKC", "Oklahoma City Thunder", ["thunder", "supersonics"]),
 ("ORL", "Orlando Magic", ["magic"]),
 ("PHI", "Philadelphia 76ers", ["76ers", "syracuse nationals"]),
 ("PHX", "Phoenix Suns", ["suns"]),
 ("POR", "Portland Trail Blazers", ["trail blazers"]),
 ("SAC", "Sacramento Kings", ["kings", "royals"]),
 ("SAS", "San Antonio Spurs", ["spurs", "chaparrals"]),
 ("TOR", "Toronto Raptors", ["raptors"]),
 ("UTA", "Utah Jazz", ["jazz"]),
 ("WAS", "Washington Wizards", ["wizards", "bullets"]),
 # defunct or merged clubs kept as their own teams
 ("MNL", "Minneapolis Lakers", []),
 ("ABA-VIR", "Virginia Squires", ["squires"]),
 ("ABA-UTS", "Utah Stars", ["utah stars"]),
 ("ABA-KEN", "Kentucky Colonels", ["colonels"]),
 ("ABA-SSL", "Spirits of St. Louis", ["spirits of st"]),
 ("ABA-SDC", "San Diego Conquistadors", ["conquistadors"]),
 ("ABA-CAR", "Carolina Cougars", ["cougars"]),
 ("ABA-OAK", "Oakland Oaks / Washington Caps", ["oakland oaks", "washington caps"]),
]
# labels that look like an NBA club name but are not (keep them out)
NOT_NBA = ["g league", "gold", "rollers", "raptors 905", "jam", "blue coats", "stars", "sizzlers", "bobcats / h"][:0]

# ---- NFL --------------------------------------------------------------------------------------------------
# Order matters: the first entry whose substring appears in the (lowercased) team label wins.
NFL = [
 ("ARI", "Arizona Cardinals", ["cardinals"]),
 ("ATL", "Atlanta Falcons", ["falcons"]),
 ("BAL", "Baltimore Ravens", ["ravens"]),
 ("BUF", "Buffalo Bills", ["bills"]),
 ("CAR", "Carolina Panthers", ["carolina panthers"]),
 ("CHI", "Chicago Bears", ["chicago bears"]),
 ("CIN", "Cincinnati Bengals", ["bengals"]),
 ("CLE", "Cleveland Browns", ["browns"]),
 ("DAL", "Dallas Cowboys", ["cowboys"]),
 ("DEN", "Denver Broncos", ["broncos"]),
 ("DET", "Detroit Lions", ["detroit lions"]),
 ("GB", "Green Bay Packers", ["packers"]),
 ("HOU", "Houston Texans", ["houston texans"]),
 ("IND", "Indianapolis Colts", ["colts"]),
 ("JAX", "Jacksonville Jaguars", ["jaguars"]),
 ("KC", "Kansas City Chiefs", ["chiefs", "dallas texans"]),
 ("LV", "Las Vegas Raiders", ["raiders"]),
 ("LAC", "Los Angeles Chargers", ["chargers"]),
 ("LAR", "Los Angeles Rams", ["rams"]),
 ("MIA", "Miami Dolphins", ["dolphins"]),
 ("MIN", "Minnesota Vikings", ["vikings"]),
 ("NE", "New England Patriots", ["patriots"]),
 ("NO", "New Orleans Saints", ["saints"]),
 ("NYG", "New York Giants", ["new york giants"]),
 ("NYJ", "New York Jets", ["jets", "new york titans"]),
 ("PHI", "Philadelphia Eagles", ["eagles"]),
 ("PIT", "Pittsburgh Steelers", ["steelers"]),
 ("SF", "San Francisco 49ers", ["49ers"]),
 ("SEA", "Seattle Seahawks", ["seahawks"]),
 ("TB", "Tampa Bay Buccaneers", ["buccaneers"]),
 ("TEN", "Tennessee Titans", ["titans", "oilers"]),
 ("WAS", "Washington Commanders", ["redskins", "commanders", "football team"]),
]

# ---- MLB --------------------------------------------------------------------------------------------------
# Specific names (city + nickname) so that minor-league and Japanese clubs (Richmond Braves, Yomiuri Giants, Hanshin Tigers)
# do not match. The Washington Senators split by year in build.franchise_of.
MLB = [
 ("ARI", "Arizona Diamondbacks", ["diamondbacks"]),
 ("ATL", "Atlanta Braves", ["atlanta braves", "milwaukee braves", "boston braves", "boston bees"]),
 ("BAL", "Baltimore Orioles", ["baltimore orioles", "st. louis browns"]),
 ("BOS", "Boston Red Sox", ["red sox"]),
 ("CHC", "Chicago Cubs", ["chicago cubs"]),
 ("CWS", "Chicago White Sox", ["white sox"]),
 ("CIN", "Cincinnati Reds", ["cincinnati reds", "cincinnati redlegs"]),
 ("CLE", "Cleveland Guardians", ["cleveland indians", "cleveland guardians"]),
 ("COL", "Colorado Rockies", ["colorado rockies"]),
 ("DET", "Detroit Tigers", ["detroit tigers"]),
 ("HOU", "Houston Astros", ["houston astros", "colt .45"]),
 ("KC", "Kansas City Royals", ["kansas city royals"]),
 ("LAA", "Los Angeles Angels", ["angels"]),
 ("LAD", "Los Angeles Dodgers", ["dodgers"]),
 ("MIA", "Miami Marlins", ["marlins"]),
 ("MIL", "Milwaukee Brewers", ["milwaukee brewers", "seattle pilots"]),
 ("MIN", "Minnesota Twins", ["minnesota twins"]),
 ("NYM", "New York Mets", ["new york mets"]),
 ("NYY", "New York Yankees", ["new york yankees"]),
 ("ATH", "Athletics", ["athletics"]),
 ("PHI", "Philadelphia Phillies", ["philadelphia phillies"]),
 ("PIT", "Pittsburgh Pirates", ["pittsburgh pirates"]),
 ("SD", "San Diego Padres", ["san diego padres"]),
 ("SF", "San Francisco Giants", ["san francisco giants", "new york giants"]),
 ("SEA", "Seattle Mariners", ["seattle mariners"]),
 ("STL", "St. Louis Cardinals", ["st. louis cardinals"]),
 ("TB", "Tampa Bay Rays", ["tampa bay"]),
 ("TEX", "Texas Rangers", ["texas rangers"]),
 ("TOR", "Toronto Blue Jays", ["toronto blue jays"]),
 ("WSH", "Washington Nationals", ["washington nationals", "montreal expos"]),
]

# ---- NHL --------------------------------------------------------------------------------------------------
# 'Winnipeg Jets' is split by year in build.franchise_of (before 1996 = the club that became the Coyotes and then Utah).
NHL = [
 ("ANA", "Anaheim Ducks", ["ducks"]),
 ("BOS", "Boston Bruins", ["bruins"]),
 ("BUF", "Buffalo Sabres", ["sabres"]),
 ("CGY", "Calgary Flames", ["flames"]),
 ("CAR", "Carolina Hurricanes", ["hurricanes", "whalers"]),
 ("CHI", "Chicago Blackhawks", ["blackhawks", "black hawks"]),
 ("COL", "Colorado Avalanche", ["avalanche", "nordiques"]),
 ("CBJ", "Columbus Blue Jackets", ["blue jackets"]),
 ("DAL", "Dallas Stars", ["dallas stars", "north stars"]),
 ("DET", "Detroit Red Wings", ["red wings"]),
 ("EDM", "Edmonton Oilers", ["edmonton oilers"]),
 ("FLA", "Florida Panthers", ["florida panthers"]),
 ("LAK", "Los Angeles Kings", ["los angeles kings"]),
 ("MIN", "Minnesota Wild", ["minnesota wild"]),
 ("MTL", "Montreal Canadiens", ["canadiens", "canadians"]),
 ("NSH", "Nashville Predators", ["predators"]),
 ("NJD", "New Jersey Devils", ["devils", "kansas city scouts", "colorado rockies"]),
 ("NYI", "New York Islanders", ["islanders"]),
 ("NYR", "New York Rangers", ["new york rangers"]),
 ("OTT", "Ottawa Senators", ["ottawa senators"]),
 ("PHI", "Philadelphia Flyers", ["flyers"]),
 ("PIT", "Pittsburgh Penguins", ["penguins"]),
 ("SJS", "San Jose Sharks", ["sharks"]),
 ("SEA", "Seattle Kraken", ["kraken"]),
 ("STL", "St. Louis Blues", ["st. louis blues"]),
 ("TBL", "Tampa Bay Lightning", ["lightning"]),
 ("TOR", "Toronto Maple Leafs", ["maple leafs", "st. patricks", "toronto arenas"]),
 ("UTA", "Utah Mammoth", ["coyotes", "utah hockey club", "utah mammoth"]),
 ("VAN", "Vancouver Canucks", ["canucks"]),
 ("VGK", "Vegas Golden Knights", ["golden knights"]),
 ("WSH", "Washington Capitals", ["capitals"]),
 ("WPG", "Winnipeg Jets", ["winnipeg jets", "atlanta thrashers", "thrashers"]),
 ("CLB", "California Golden Seals / Cleveland Barons", ["golden seals", "oakland seals", "california seals", "cleveland barons"]),
]
