"""Search and answer-engine copy for every /games/ page, kept apart from the page markup.

Each entry feeds scripts/gen_games_pages.py: the <title>, meta description, the one-paragraph answer shown at the top
of the page (also marked as speakable), HowTo steps for JSON-LD, tips, related games and the share-card file.
Voice: calm, plain, specific. No marketing words, no emojis, no dashes.
"""

SITE_NAME = "Purplelink"
FOUNDED = "2026-10-04"   # games section launch date

GAMES = {
    "games/linkle/": dict(
        slug="linkle", name="Linkle", genre="Word game", minutes=3,
        title="Linkle: a free daily five-letter word game with a new twist each day",
        desc="Guess the hidden five-letter word in six tries. Linkle is free, has a new word every day and a different twist each weekday, and needs no account.",
        answer="Linkle is a free daily word game. Guess the hidden five-letter word in six tries, using the colored tiles as clues. A new word arrives at midnight, and each weekday adds its own twist: a revealed first letter, an extra guess, a vowel count, and more.",
        features=["Six guesses to find a five-letter word", "A different rule every weekday", "Ranks and a weekly tracker", "Share your result as plain text, with no spoilers"],
        steps=[("Type a five-letter word", "Use your keyboard or the on-screen keys, then press Enter. The word must be in the word list."),
               ("Read the tiles", "Purple means the right letter in the right place. Striped yellow means the letter is in the word somewhere else. Gray means it is not in the word."),
               ("Check the day's twist", "The banner above the board states today's rule, such as a revealed first letter or a seventh guess."),
               ("Solve it in six tries or fewer", "Use each result to narrow the possibilities, then copy your result to share it.")],
        tips=["Open with a word that uses common, different letters, such as a mix of vowels and consonants, so the first row tells you as much as possible.",
              "A guess does not have to be a possible answer. Use it to test letters you have not tried yet.",
              "A word can contain the same letter twice. A tile marked present for one E does not rule out a second E.",
              "On Friday the answer never repeats a letter and on Saturday it always does, which narrows the list quickly.",
              "On Sunday's hard mode, every hint you have found has to be used in your next guess, so plan two guesses ahead."],
        related=["quadlink", "sudoku", "crossword"], og_photo="dsc-3940"),
    "games/quadlink/": dict(
        slug="quadlink", name="Quadlink", genre="Word game", minutes=5,
        title="Quadlink: a free daily four-board word game",
        desc="Solve four five-letter words at once in nine guesses. Quadlink is a free daily word puzzle where every guess is scored on all four boards.",
        answer="Quadlink is a free daily word game where you solve four hidden five-letter words at once in nine guesses. Every guess is scored against all four boards at the same time, so a good guess works four times over.",
        features=["Four boards, nine guesses", "One shared keyboard with a bar per board", "Free, no account needed"],
        steps=[("Enter a five-letter word", "Type it and press Enter. The same guess is checked against all four boards."),
               ("Read each board", "Each board uses the same colors as Linkle: purple for right, striped yellow for misplaced, gray for absent."),
               ("Watch the keyboard bars", "Under each key, four small bars show what is known about that letter on boards one to four."),
               ("Solve all four", "A board stops taking guesses once you solve it. You win when all four are solved within nine guesses.")],
        tips=["Start with two or three words that cover many different letters before you commit to any one board.",
              "Finish the board that is closest to solved first, because its guesses also feed the others.",
              "Prefer valid words that fit more than one board, since one guess can score on several at once.",
              "Letters can repeat across boards, so a gray tile on one board says nothing about the others."],
        related=["linkle", "sudoku", "daily-five"], og_photo="dsc-8610"),
    "games/daily-five/": dict(
        slug="daily-five", name="Daily Five", genre="Trivia game", minutes=2,
        title="Daily Five: a free daily trivia quiz with five questions",
        desc="Five multiple-choice trivia questions a day on science, computing, research, geography and more. Free, a new set every midnight, and no account needed.",
        answer="Daily Five is a free daily trivia quiz with five multiple-choice questions. Two come from a set about science, computing, research methods and Macs, and three come from a general trivia pool. Everyone gets the same five each day.",
        features=["Five questions a day", "Immediate right or wrong feedback", "Streak and percentile against other players"],
        steps=[("Read the question", "Each question shows a category and four answers."),
               ("Pick one answer", "You see at once whether it was right, and the correct answer if it was not."),
               ("Move to the next question", "There are five in total. You cannot change an answer once chosen."),
               ("See your score", "Your score, streak and how you compared with other players appear after the fifth question.")],
        tips=["Eliminate the answers you know are wrong first, then choose between what is left.",
              "The research and computing questions favor precise definitions, so read each option to the end.",
              "A streak counts any finished set, whatever your score, so a bad day does not break it."],
        related=["daily-photo", "daily-chess", "crossword"], og_photo="dsc-7888"),
    "games/daily-photo/": dict(
        slug="daily-photo", name="Daily Photo", genre="Geography game", minutes=2,
        title="Daily Photo: guess the country in five travel photographs",
        desc="Five travel photographs a day. Pick which of four countries each was taken in, then see the exact place. Free, with no third-party ads and no account.",
        answer="Daily Photo is a free daily geography game. Each day shows five travel photographs, and you pick which of four countries each one was taken in. After every answer you see the exact place and a short description of the photograph.",
        features=["Five photographs a day from ten countries", "The exact place and a caption after each answer", "Photographs by Ben Ampel"],
        steps=[("Look at the photograph", "Take in the architecture, landscape, signs and light."),
               ("Choose a country", "Pick one of four countries."),
               ("Read the reveal", "You see the exact place, a short description and a link to more photographs from there."),
               ("Finish all five", "Your score and a shareable result appear after the fifth photograph.")],
        tips=["Look for architecture, vegetation and the quality of the light before you guess.",
              "Mountains with alpine meadows point toward Switzerland, black volcanic sand and waterfalls toward Iceland, and torii gates toward Japan.",
              "If two options both seem plausible, the one with more distinctive landmarks in the frame is usually right."],
        related=["daily-five", "daily-chess", "linkle"], og_photo="dsc-3638"),
    "games/daily-chess/": dict(
        slug="daily-chess", name="Daily Chess", genre="Chess puzzle", minutes=3,
        title="Daily Chess Puzzle: a free Lichess puzzle every day",
        desc="A free daily chess tactics puzzle from the Lichess puzzle database, easier on Monday and harder through the week. Find the best moves. No account needed.",
        answer="Daily Chess is a free daily chess tactics puzzle drawn from the Lichess puzzle database. Find the best move, then the follow-up, to win material or deliver checkmate. Monday's puzzle is the easiest and Sunday's is the hardest.",
        features=["One tactics puzzle a day from the Lichess puzzle database (CC0)", "Difficulty rises from Monday to Sunday", "Hints, a streak and a percentile against other players"],
        steps=[("Study the position", "The side to move is shown at the bottom of the board. The last move played is highlighted."),
               ("Make your move", "Click the piece, then click the square you want it to go to. Legal moves are shown with a dot."),
               ("Keep going", "After a correct move the opponent replies and you play the next move until the puzzle is won."),
               ("Use a hint if you are stuck", "A hint points to the piece to move. Hints and wrong moves count as slips in your result.")],
        tips=["Check every forcing move first: checks, captures and direct threats.",
              "Ask what the opponent's last move left undefended or attacked.",
              "Look for the patterns that decide most puzzles: forks, pins, skewers, discovered attacks and back-rank mates.",
              "When a puzzle says mate in two, count the opponent's possible replies before you commit."],
        related=["sudoku", "daily-five", "linkle"], og_photo="dsc-7919"),
    "games/sudoku/": dict(
        slug="sudoku", name="Sudoku", genre="Logic puzzle", minutes=12,
        title="Daily Sudoku: a free puzzle that gets harder every week",
        desc="A new Sudoku every day with one solution. Each week is harder than the last across a ten-week season, from Beginner to Expert. Free, with notes and checking.",
        answer="Daily Sudoku is a free daily Sudoku with exactly one solution. Difficulty rises every week across a ten-week season, from Beginner in the first two weeks to Expert in the last two, and then a new season starts.",
        features=["Unique-solution puzzles", "Ten-week seasons that get harder every week", "Pencil notes, checking and an optional auto-check", "Best time per difficulty level"],
        steps=[("Select a square", "Click it, or use the arrow keys to move around the grid."),
               ("Enter a digit", "Type 1 to 9 or use the number pad. Every row, column and 3 by 3 box must contain each digit once."),
               ("Use notes for candidates", "Turn on Notes to pencil small digits into a square without committing to them."),
               ("Check your work", "Duplicates turn red automatically. Check can test one square or the whole grid, and Auto-check flags wrong digits as you type.")],
        tips=["Start by scanning each digit: look for the one square in a row, column or box where that digit can go.",
              "Pencil notes pay off in the later weeks. Mark candidates, then look for pairs that share two candidates in a unit.",
              "When stuck, pick the row, column or box with the most digits already placed.",
              "From Hard onward, look for X-Wing patterns: a digit that appears in only two squares in each of two rows, in the same two columns."],
        related=["chess-puzzles", "crossword", "linkle"], og_photo="dsc-6626-edit"),
    "games/crossword/": dict(
        slug="crossword", name="Daily Crossword", genre="Crossword puzzle", minutes=10,
        title="Daily Crossword: a free themeless puzzle, easy Monday to hard Sunday",
        desc="A new free crossword every day, easiest on Monday and hardest on Sunday, with letter, word and puzzle checking. No account needed and no third-party ads.",
        answer="Daily Crossword is a free daily themeless crossword puzzle. The grid grows and the clues get trickier from Monday to Sunday, and you can check one letter, one word or the whole puzzle, or turn on auto-check.",
        features=["Grids from 9 by 9 on Monday to 15 by 15 on Sunday", "Check a letter, a word or the puzzle, plus auto-check", "Reveal a letter, a word or the puzzle", "Best time per weekday for unaided solves"],
        steps=[("Select a clue or a square", "Click a square and type. Click it again, or press Space, to switch between across and down."),
               ("Fill in the answers", "Arrow keys move around the grid, Tab jumps to the next clue and Backspace deletes."),
               ("Check as you go", "Check a letter, a word or the whole puzzle, or turn on auto-check to flag wrong letters as you type."),
               ("Finish the grid", "When every square is right you see your time, streak and best time for that weekday.")],
        tips=["Fill in the short answers you are sure of first, since they give you crossing letters for the long ones.",
              "Plurals usually end in S, and past-tense clues usually end in ED. The clue matches the answer's tense and number.",
              "A question mark at the end of a clue means light wordplay.",
              "On a phone, tap a square and use the on-screen keyboard. Tap the same square again to switch direction."],
        related=["sudoku-unlimited", "linkle", "daily-five"], og_photo="dsc-4267"),
    "games/daily-stars/": dict(
        slug="daily-stars", name="Daily Stars", genre="Horoscope", minutes=1,
        title="Daily Stars: a short daily horoscope for every sign",
        desc="A short, plain daily reading for each of the twelve zodiac signs, written for entertainment. Free, new every day, and no account needed.",
        answer="Daily Stars is a free daily horoscope with a short reading for each of the twelve zodiac signs. The readings are written for entertainment and are not advice. A new set appears at midnight.",
        features=["A reading for each of the twelve signs", "The day's approximate moon phase", "Written for entertainment only"],
        steps=[("Choose your sign", "Pick your zodiac sign from the grid. The date ranges are shown on each button."),
               ("Read today's entry", "Each reading is two short sentences: a note on the day and a nudge for your sign."),
               ("Check the other signs", "Open any other sign from the list at the bottom of the page.")],
        tips=["Treat the readings as a prompt for the day, not a prediction.",
              "Your chosen sign is remembered in this browser, or on your account if you sign in."],
        related=["daily-photo", "daily-five", "linkle"], og_photo="dsc-8053"),
    "games/chess-puzzles/": dict(
        slug="chess-puzzles", name="Chess Puzzles", genre="Chess puzzle", minutes=2,
        title="Chess Puzzles: unlimited rated tactics from the Lichess database",
        desc="Free, unlimited chess puzzles with a rating that rises and falls as you solve. Puzzles come from the Lichess database. Sign in to join the leaderboard.",
        answer="Chess Puzzles is a free, unlimited chess tactics trainer. Each puzzle is picked near your rating from the Lichess puzzle database. Solve it and your rating goes up, miss it and it goes down, with no daily limit.",
        features=["Unlimited puzzles, picked near your rating", "Rush: three minutes, as many as you can", "An Elo-style puzzle rating", "Optional leaderboard for signed-in players", "Puzzles from the Lichess database (CC0)"],
        steps=[("See the position", "The opponent has just moved. Find the best move for the side shown at the bottom of the board."),
               ("Play your moves", "Click a piece, then its destination square. After each correct move the opponent replies and you continue."),
               ("Solve or miss", "The first wrong move ends the puzzle and shows the correct line. A checkmate always counts."),
               ("Watch your rating", "A solve raises your rating, more so when the puzzle is rated above you. A miss lowers it. Then take the next puzzle.")],
        tips=["Check every forcing move first: checks, captures and threats, in that order.",
              "Look at what the opponent's last move changed. Puzzles start right after a mistake or a sacrifice.",
              "Ratings settle after about 20 puzzles, so do not read much into the first few results.",
              "If you cannot see it in a minute, use Show solution. It counts as a miss, but reading the line is still practice.",
              "Easier puzzles gain little when you solve them and cost a lot when you miss, so a streak of easy wins is not a shortcut."],
        related=["daily-chess", "sudoku-unlimited", "leaderboard"], og_photo="dsc-6626-edit"),
    "games/sudoku-unlimited/": dict(
        slug="sudoku-unlimited", name="Sudoku Unlimited", genre="Logic puzzle", minutes=10,
        title="Sudoku Unlimited: free rated Sudoku, one puzzle after another",
        desc="Unlimited free Sudoku in five levels, from Beginner to Expert, with a rating that follows how fast and how cleanly you solve. Sign in to join the leaderboard.",
        answer="Sudoku Unlimited is a free Sudoku with no daily limit. Puzzles come in five levels, each with exactly one solution, and your rating moves with the level you solve and how quickly and cleanly you solve it.",
        features=["Five levels, Beginner to Expert", "Every puzzle has exactly one solution", "Notes, check and auto-check", "A rating based on level, time and help used", "Optional leaderboard for signed-in players"],
        steps=[("Fill the grid", "Every row, column and 3 by 3 box must contain the digits 1 to 9 once."),
               ("Use notes for candidates", "Turn notes on to pencil small digits into a square, then remove them as you rule them out."),
               ("Solve without help for the best gain", "Check and reveal still work, but a solve that used them moves your rating less."),
               ("Take the next puzzle", "The level follows your rating: it rises as you solve, and eases when you struggle.")],
        tips=["Scan for squares where only one digit fits before you start using notes.",
              "On Hard and Expert, look for pairs and triples of candidates in a row, column or box.",
              "Solving faster than the level's pace earns a larger gain; slow solves still count as solves.",
              "New puzzle on an unfinished grid counts as a miss, so finish or skip deliberately.",
              "Ratings settle after about 20 puzzles."],
        related=["sudoku", "chess-puzzles", "leaderboard"], og_photo="dsc-4267"),
    "games/leaderboard/": dict(
        slug="leaderboard", name="Leaderboards", genre="Ratings", minutes=1,
        title="Puzzle leaderboards: top Chess Puzzles and Sudoku ratings",
        desc="The top players in Chess Puzzles and Sudoku Unlimited, by rating and by rating gained this week. Players join by choice, with a display name.",
        answer="The Purplelink puzzle leaderboards list the highest ratings in Chess Puzzles and Sudoku Unlimited, plus the biggest rating gains this week. Only signed-in players who choose to appear are listed, under their display name.",
        features=["Top 100 by rating for chess and Sudoku", "Weekly board for rating gained since Monday", "Opt-in, with a display name only"],
        steps=[("Play rated puzzles", "Solve puzzles in Chess Puzzles or Sudoku Unlimited."),
               ("Sign in", "Use the email link on your account page so your rating is kept on the server."),
               ("Pick a display name", "Choose a name on the account page. It is the only thing shown."),
               ("Join the board", "Turn on the leaderboard on the account page or after a puzzle. You can leave at any time.")],
        tips=["The weekly board needs at least three rated puzzles that week and resets on Monday.",
              "Ratings are server-checked: the rating service only accepts reports for real puzzles in a plausible time.",
              "You can switch the leaderboard off at any time and your row is removed."],
        related=["chess-puzzles", "sudoku-unlimited", "daily-chess"], og_photo="dsc-3940"),
    "games/landlink/": dict(
        slug="landlink", name="Landlink", genre="Geography game", minutes=3,
        title="Landlink: a free daily country guessing game with clues",
        desc="Guess the mystery country in eight tries. Each guess shows how its continent, region, population, area, coast, driving side and income compare. Free, new every day.",
        answer="Landlink is a free daily geography game. Guess the mystery country in eight tries. After each guess, every column (continent, region, population, area, coast, driving side and income group) shows whether you matched, were close, or were off, with an arrow for the numbers.",
        features=["Eight guesses, one country a day", "Seven comparable facts per country", "Arrows show higher or lower", "Open data: Natural Earth and Wikidata"],
        steps=[("Type a country", "Pick it from the list as you type."),
               ("Read the row", "Purple means the same. Striped yellow means close, or a number within range. An arrow points the way for numbers."),
               ("Narrow it down", "Continent and region first, then population and area, then coast and driving side."),
               ("Solve in eight or fewer", "A hint with the first letter appears after four guesses.")],
        tips=["Start with a large, central country such as India or Brazil to learn the continent, region and size at once.",
              "Population and area arrows point to where the answer sits, so use them to halve the options.",
              "Driving side and coast split the list quickly once the region is known."],
        related=["atomlink", "prizelink", "daily-photo"], og_photo="dsc-3638"),
    "games/atomlink/": dict(
        slug="atomlink", name="Atomlink", genre="Science game", minutes=3,
        title="Atomlink: a free daily periodic table guessing game",
        desc="Guess the mystery chemical element in eight tries. Each guess compares atomic number, period, category, state, mass and year of discovery. Free, new every day.",
        answer="Atomlink is a free daily chemistry game. Guess the mystery element in eight tries. After each guess, every column (atomic number, period, category, state, atomic mass and year of discovery) shows whether you matched, were close, or were off, with an arrow for the numbers.",
        features=["Eight guesses, one element a day", "Six comparable properties per element", "Arrows show higher or lower", "Data from PubChem (public domain)"],
        steps=[("Type an element", "Use the name or the symbol, such as Fe."),
               ("Read the row", "Purple means the same. Striped yellow means close. An arrow points the way for numbers."),
               ("Use the table", "Period and category place the element on the periodic table; number and mass narrow it within that."),
               ("Solve in eight or fewer", "A hint appears after four guesses.")],
        tips=["Open with a transition metal such as iron to learn the category and an approximate number.",
              "Ancient elements all count as discovered long ago, so the year is only a clue for the rest.",
              "State at room temperature splits gases and liquids from the many solids."],
        related=["landlink", "prizelink", "daily-five"], og_photo="dsc-8053"),
    "games/prizelink/": dict(
        slug="prizelink", name="Prizelink", genre="Trivia game", minutes=3,
        title="Prizelink: a free daily Nobel laureate guessing game",
        desc="Guess the mystery Nobel laureate in eight tries. Each guess compares prize, year, birth year, age at the prize, where they were born and gender. Free, new every day.",
        answer="Prizelink is a free daily game about Nobel laureates. Guess the mystery laureate in eight tries. After each guess, every column (prize, year, birth year, age at the prize, continent, country and gender) shows whether you matched, were close, or were off, with an arrow for the numbers.",
        features=["Eight guesses, one laureate a day", "Well-known laureates only as answers, all laureates as guesses", "Arrows show higher or lower", "Data from the Nobel Prize API (CC0)"],
        steps=[("Type a name", "Pick a laureate from the list as you type."),
               ("Read the row", "Purple means the same. Striped yellow means close. An arrow points the way for numbers."),
               ("Work from the prize", "Field and year place the person; birth year and age narrow it."),
               ("Solve in eight or fewer", "A hint appears after four guesses.")],
        tips=["Start with a physics or literature laureate from the early 1900s to learn the era quickly.",
              "The age at the prize is usually between 50 and 80, so the arrow helps most on the extremes.",
              "Country is the birth country as it is named today."],
        related=["landlink", "atomlink", "daily-five"], og_photo="dsc-7888"),
    "games/citylink/": dict(
        slug="citylink", name="Citylink", genre="Geography game", minutes=3,
        title="Citylink: a free daily city guessing game with map clues",
        desc="Guess the mystery city in eight tries. Each guess compares continent, country, population, latitude, longitude and whether it is a capital. Free, new every day.",
        answer="Citylink is a free daily geography game. Guess the mystery city in eight tries. After each guess, every column (continent, country, population, latitude, longitude and capital status) shows whether you matched, were close, or were off, and the latitude and longitude arrows point north, south, east or west.",
        features=["Eight guesses, one city a day", "Latitude and longitude arrows act like a compass", "700 cities to guess from", "Open data: Natural Earth"],
        steps=[("Type a city", "Pick it from the list as you type."),
               ("Read the row", "Purple means the same. Striped yellow means close. An arrow points the way for numbers."),
               ("Use the compass", "A latitude arrow up means the answer is further north; a longitude arrow up means further east."),
               ("Solve in eight or fewer", "A hint appears after four guesses.")],
        tips=["Start with a city near the middle of the map, such as Cairo or Istanbul, so the arrows have room to point both ways.",
              "Continent and country rule out most of the list; latitude and longitude then narrow it to a region.",
              "Capital status is a quick yes or no that halves what is left."],
        related=["landlink", "peaklink", "daily-photo"], og_photo="dsc-3638"),
    "games/peaklink/": dict(
        slug="peaklink", name="Peaklink", genre="Geography game", minutes=3,
        title="Peaklink: a free daily mountain guessing game",
        desc="Guess the mystery mountain in eight tries. Each guess compares continent, country, height, latitude, longitude and whether it is a volcano. Free, new every day.",
        answer="Peaklink is a free daily geography game about mountains. Guess the mystery peak in eight tries. After each guess, every column (continent, country, height, latitude, longitude and volcano) shows whether you matched, were close, or were off, with arrows for the numbers.",
        features=["Eight guesses, one mountain a day", "Countries are a set, so shared peaks count as partly right", "Height, latitude and longitude arrows", "Open data: Wikidata (CC0)"],
        steps=[("Type a mountain", "Pick it from the list as you type."),
               ("Read the row", "Purple means the same. Striped yellow means close, or a shared country. An arrow points the way for numbers."),
               ("Home in", "Height and the compass arrows narrow the range; volcano splits the list."),
               ("Solve in eight or fewer", "A hint appears after four guesses.")],
        tips=["Try a famous high peak first: its height arrow tells you whether to go up or down the range of altitudes.",
              "Peaks on a border list two countries, and sharing one counts as close.",
              "Volcanoes cluster along a few belts, so a yes narrows the map fast."],
        related=["citylink", "landlink", "atomlink"], og_photo="dsc-8610"),
    "games/codelink/": dict(
        slug="codelink", name="Codelink", genre="Tech game", minutes=3,
        title="Codelink: a free daily programming language guessing game",
        desc="Guess the mystery programming language in eight tries. Each guess compares first release, typing, how it runs, memory model, use and style. Free, new every day.",
        answer="Codelink is a free daily game about programming languages. Guess the mystery language in eight tries. After each guess, every column (first release, typing, how it runs, memory model, main use and programming style) shows whether you matched, were close, or were off.",
        features=["Eight guesses, one language a day", "63 languages from Fortran to Zig", "Style is a set, so partly shared styles count as close", "Our own hand-checked table"],
        steps=[("Type a language", "Pick it from the list as you type."),
               ("Read the row", "Purple means the same. Striped yellow means close, or some shared styles. An arrow points the way for the year."),
               ("Use the clues", "Typing and memory split languages into families; use narrows the field."),
               ("Solve in eight or fewer", "A hint appears after four guesses.")],
        tips=["Open with a language from the 1990s such as Java or Python to learn the era and the family at once.",
              "Memory model is a strong clue: manual, garbage collected, reference counted or ownership.",
              "The style column is a set, so a guess that shares two of three styles shows as close."],
        related=["atomlink", "prizelink", "daily-five"], og_photo="dsc-7888"),
    "games/thinkerlink/": dict(
        slug="thinkerlink", name="Thinkerlink", genre="Science game", minutes=3,
        title="Thinkerlink: a free daily scientist guessing game",
        desc="Guess the mystery scientist in eight tries. Each guess compares field, birth year, lifespan, birthplace and gender. Free, new every day.",
        answer="Thinkerlink is a free daily game about famous scientists. Guess the mystery scientist in eight tries. After each guess, every column (field, birth year, lifespan, continent, country and gender) shows whether you matched, were close, or were off, with arrows for the numbers.",
        features=["Eight guesses, one scientist a day", "131 scientists from Vesalius to Hinton", "Arrows show earlier or later, longer or shorter", "Our own checked table"],
        steps=[("Type a name", "Pick a scientist from the list as you type."),
               ("Read the row", "Purple means the same. Striped yellow means close. An arrow points the way for numbers."),
               ("Place them in time", "The birth year arrow tells you whether to look earlier or later."),
               ("Solve in eight or fewer", "A hint appears after four guesses.")],
        tips=["Start with someone from the 1800s, such as Darwin or Faraday, so the birth year arrow can point either way.",
              "Field splits the list into seven groups; birthplace then narrows it.",
              "Lifespan shows 'Living' for scientists who are still alive, which is a quick filter."],
        related=["prizelink", "atomlink", "daily-five"], og_photo="dsc-7888"),
    "games/riverlink/": dict(
        slug="riverlink", name="Riverlink", genre="Geography game", minutes=3,
        title="Riverlink: a free daily river guessing game",
        desc="Guess the mystery river in eight tries. Each guess compares continent, countries, length and where it flows. Free, new every day.",
        answer="Riverlink is a free daily geography game about rivers. Guess the mystery river in eight tries. After each guess, every column (continent, countries, how many countries, length, what it flows into and where it ends) shows whether you matched, were close, or were off.",
        features=["Eight guesses, one river a day", "Countries are a set, so shared countries count as close", "Length arrow", "Open data: Wikidata (CC0)"],
        steps=[("Type a river", "Pick it from the list as you type."),
               ("Read the row", "Purple means the same. Striped yellow means close, or a shared country. An arrow points the way for numbers."),
               ("Follow the water", "What a river flows into narrows the region fast: a sea, a lake or another river."),
               ("Solve in eight or fewer", "A hint appears after four guesses.")],
        tips=["A very long river such as the Nile or Amazon shows you the length range at once.",
              "Rivers that share a country with the answer show as close, even when the continent differs.",
              "Tributaries share what they flow into, so a match there points to one river system."],
        related=["landlink", "peaklink", "citylink"], og_photo="dsc-8610"),
    "games/wildlink/": dict(
        slug="wildlink", name="Wildlink", genre="Nature game", minutes=3,
        title="Wildlink: a free daily animal guessing game",
        desc="Guess the mystery animal in eight tries. Each guess compares group, diet, habitat, continents, weight and lifespan. Free, new every day.",
        answer="Wildlink is a free daily game about animals. Guess the mystery animal in eight tries. After each guess, every column (group, diet, where it lives, continents, typical weight and typical lifespan) shows whether you matched, were close, or were off, with arrows for the numbers.",
        features=["Eight guesses, one animal a day", "92 animals from ants to blue whales", "Continents are a set, so shared ranges count as close", "Our own checked table"],
        steps=[("Type an animal", "Pick it from the list as you type."),
               ("Read the row", "Purple means the same. Striped yellow means close. An arrow points the way for numbers."),
               ("Use size and life", "Weight and lifespan can span a huge range, so the arrows help most early."),
               ("Solve in eight or fewer", "A hint appears after four guesses.")],
        tips=["Weight is the strongest clue: start with a mid-sized animal such as a wolf to see which way to go.",
              "Group and diet split the list quickly; habitat then separates ocean animals from land animals.",
              "Weights and lifespans are typical adult values, not records."],
        related=["landlink", "peaklink", "daily-photo"], og_photo="dsc-3940"),
    "games/teamlink/": dict(
        slug="teamlink", name="Teamlink", genre="Sports game", minutes=4,
        title="Teamlink: a free daily sports teammate-chain game",
        desc="Link two players from any era through a chain of real teammates, such as LeBron James to Anthony Davis to Cooper Flagg. NBA, NFL, MLB and NHL. Free, new every day.",
        answer="Teamlink is a free daily sports puzzle. You are given two well-known players, often from different eras, and you build the shortest chain of real teammates between them, for example LeBron James to Anthony Davis to Cooper Flagg. Add a player at either end of the chain. Each new player must have shared a team and a season with the player next to him. The sport changes each day across the NBA, NFL, MLB and NHL.",
        features=["A new pair of players every day", "Stars from every era, no bench players", "Add players at either end of the chain", "Hints, undo and unlimited practice", "NBA, NFL, MLB and NHL"],
        steps=[("Read the two players", "Each card shows the position, the years played and the teams."),
               ("Name a teammate", "Type a player who shared a team and a season with either end of your chain."),
               ("Close the gap", "The chain is solved when its two ends are teammates."),
               ("Match par", "Par is the shortest possible chain. Fewer misses and no hints earn three stars.")],
        tips=["Work from both ends. A player who spent many years with one team is the easiest bridge.",
              "Players who changed teams often are the best connectors between eras.",
              "Teammates need overlapping seasons, not just the same team, so check the years on each card."],
        related=["gridlink", "unbeaten", "daily-five"], og_photo="dsc-3940"),
    "games/gridlink/": dict(
        slug="gridlink", name="Gridlink", genre="Sports game", minutes=4,
        title="Gridlink: a free daily sports grid game",
        desc="Fill a 3 by 3 grid with players who fit both the row and the column: a team, a decade, an award or a teammate. NBA, NFL, MLB and NHL. Nine guesses, free, new every day.",
        answer="Gridlink is a free daily sports grid. Each row and column is a clue, such as a team, a decade, an award or a famous teammate, and each cell needs a player who fits both. You get nine guesses and can use each player once. The rarer the player you name, the more points the cell is worth. The sport changes each day across the NBA, NFL, MLB and NHL.",
        features=["Nine guesses for nine cells", "Teams, decades, positions, awards and famous teammates as clues", "Rarity score for less obvious players", "Unlimited practice grids", "NBA, NFL, MLB and NHL"],
        steps=[("Pick a cell", "Tap a cell to see which row and column clues it joins."),
               ("Name a player", "Type a name and pick it from the list. The player must fit both clues."),
               ("Watch your guesses", "A wrong name still uses one of your nine guesses."),
               ("Go for rarity", "Each cell scores 1 to 5, higher for less famous players.")],
        tips=["Start with the cell that has two teams. Few players fit it, so the answer is easier to pin down.",
              "A player who fits several cells is worth saving for the hardest one.",
              "Decade clues count any season in that decade, so a career that spans two decades fits both."],
        related=["teamlink", "unbeaten", "landlink"], og_photo="dsc-3940"),
    "games/unbeaten/": dict(
        slug="unbeaten", name="Unbeaten", genre="Sports game", minutes=5,
        title="Unbeaten: build a team from any era and play a perfect season",
        desc="Build a roster from any era under a budget, then play a full season. Can your team go undefeated? NBA, NFL, MLB and NHL. Free, with a daily challenge.",
        answer="Unbeaten is a free sports team builder. Pick a starting lineup and bench from players of any era under a budget, then play a full season and a playoff run. The result comes from each player's rating, a bonus for players who really were teammates, and a seeded random draw. Going undefeated is possible but very rare, and the game shows the exact chance for your roster. A daily challenge changes the rules each weekday.",
        features=["Players from every era under one budget", "A full regular season and playoffs", "The exact chance of going undefeated", "A new rule every weekday", "NBA, NFL, MLB and NHL"],
        steps=[("Fill every starting spot", "Each spot needs a player at that position. The bench takes anyone."),
               ("Watch the budget", "Better players cost more, and the budget does not cover a team of stars."),
               ("Look for teammates", "Players who really played together add a small chemistry bonus."),
               ("Play the season", "See your record, your playoff run and your chance of a perfect season.")],
        tips=["A few stars with solid role players usually beats a lineup of mid-priced players.",
              "Old teammates add chemistry, so a pair from the same great team can beat two stronger strangers.",
              "Ratings come mostly from career honors such as All-Star selections, MVPs and titles, and do not adjust for era."],
        related=["teamlink", "gridlink", "daily-five"], og_photo="dsc-3940"),
}

HUB = dict(
    title="Free daily games: Linkle, Sudoku, crossword, chess and more",
    desc="Free daily puzzles from Purplelink: a word game, a four-board word game, trivia, photo geography, chess, Sudoku, a crossword and a horoscope. New every midnight.",
    answer="Purplelink's daily games are a set of free puzzles that change every day at midnight: Linkle, Quadlink, Daily Five trivia, Daily Photo, Daily Chess, Sudoku, a themeless crossword and Daily Stars, plus guessing games about countries, cities, animals and more, and three sports games (Teamlink, Gridlink and Unbeaten) covering the NBA, NFL, MLB and NHL. You can play without an account. The daily games have no third-party ads. Chess Puzzles and Sudoku Unlimited add unlimited rated puzzles and leaderboards, and show Google ads.",
    og_photo="dsc-3940",
)
