"""Search and answer-engine copy for every /games/ page, kept apart from the page markup.

Each entry feeds scripts/gen_games_pages.py: the <title>, meta description, the one-paragraph answer shown at the top
of the page (also marked as speakable), HowTo steps for JSON-LD, tips, related games and the share-card file.
Voice: calm, plain, specific. No marketing words, no emojis, no dashes.
"""

SITE_NAME = "Purplelink"
FOUNDED = "2026-10-04"   # games section launch date

GAMES = {
    "games/linkle/": dict(
        slug="linkle", name="Linkle", genre="Word game", minutes=3,
        title="Linkle: a free daily five-letter word game with a new twist each day",
        desc="Guess the hidden five-letter word in six tries. Linkle is free, has a new word every day and a different twist each weekday, and needs no account.",
        answer="Linkle is a free daily word game. Guess the hidden five-letter word in six tries, using the colored tiles as clues. A new word arrives at midnight, and each weekday adds its own twist: a revealed first letter, an extra guess, a vowel count, and more.",
        features=["Six guesses to find a five-letter word", "A different rule every weekday", "Ranks and a weekly tracker", "Share your result as plain text, with no spoilers"],
        steps=[("Type a five-letter word", "Use your keyboard or the on-screen keys, then press Enter. The word must be in the word list."),
               ("Read the tiles", "Purple means the right letter in the right place. Striped yellow means the letter is in the word somewhere else. Gray means it is not in the word."),
               ("Check the day's twist", "The banner above the board states today's rule, such as a revealed first letter or a seventh guess."),
               ("Solve it in six tries or fewer", "Use each result to narrow the possibilities, then copy your result to share it.")],
        tips=["Open with a word that uses common, different letters, such as a mix of vowels and consonants, so the first row tells you as much as possible.",
              "A guess does not have to be a possible answer. Use it to test letters you have not tried yet.",
              "A word can contain the same letter twice. A tile marked present for one E does not rule out a second E.",
              "On Friday the answer never repeats a letter and on Saturday it always does, which narrows the list quickly.",
              "On Sunday's hard mode, every hint you have found has to be used in your next guess, so plan two guesses ahead."],
        related=["quadlink", "sudoku", "crossword"], og_photo="dsc-3940"),
    "games/quadlink/": dict(
        slug="quadlink", name="Quadlink", genre="Word game", minutes=5,
        title="Quadlink: a free daily four-board word game",
        desc="Solve four five-letter words at once in nine guesses. Quadlink is a free daily word puzzle where every guess is scored on all four boards.",
        answer="Quadlink is a free daily word game where you solve four hidden five-letter words at once in nine guesses. Every guess is scored against all four boards at the same time, so a good guess works four times over.",
        features=["Four boards, nine guesses", "One shared keyboard with a bar per board", "Free, no account needed"],
        steps=[("Enter a five-letter word", "Type it and press Enter. The same guess is checked against all four boards."),
               ("Read each board", "Each board uses the same colors as Linkle: purple for right, striped yellow for misplaced, gray for absent."),
               ("Watch the keyboard bars", "Under each key, four small bars show what is known about that letter on boards one to four."),
               ("Solve all four", "A board stops taking guesses once you solve it. You win when all four are solved within nine guesses.")],
        tips=["Start with two or three words that cover many different letters before you commit to any one board.",
              "Finish the board that is closest to solved first, because its guesses also feed the others.",
              "Prefer valid words that fit more than one board, since one guess can score on several at once.",
              "Letters can repeat across boards, so a gray tile on one board says nothing about the others."],
        related=["linkle", "sudoku", "daily-five"], og_photo="dsc-8610"),
    "games/daily-five/": dict(
        slug="daily-five", name="Daily Five", genre="Trivia game", minutes=2,
        title="Daily Five: a free daily trivia quiz with five questions",
        desc="Five multiple-choice trivia questions a day on science, computing, research, geography and more. Free, a new set every midnight, and no account needed.",
        answer="Daily Five is a free daily trivia quiz with five multiple-choice questions. Two come from a set about science, computing, research methods and Macs, and three come from a general trivia pool. Everyone gets the same five each day.",
        features=["Five questions a day", "Immediate right or wrong feedback", "Streak and percentile against other players"],
        steps=[("Read the question", "Each question shows a category and four answers."),
               ("Pick one answer", "You see at once whether it was right, and the correct answer if it was not."),
               ("Move to the next question", "There are five in total. You cannot change an answer once chosen."),
               ("See your score", "Your score, streak and how you compared with other players appear after the fifth question.")],
        tips=["Eliminate the answers you know are wrong first, then choose between what is left.",
              "The research and computing questions favor precise definitions, so read each option to the end.",
              "A streak counts any finished set, whatever your score, so a bad day does not break it."],
        related=["daily-photo", "daily-chess", "crossword"], og_photo="dsc-7888"),
    "games/daily-photo/": dict(
        slug="daily-photo", name="Daily Photo", genre="Geography game", minutes=2,
        title="Daily Photo: guess the country in five travel photographs",
        desc="Five travel photographs a day. Pick which of four countries each was taken in, then see the exact place. Free, with no third-party ads and no account.",
        answer="Daily Photo is a free daily geography game. Each day shows five travel photographs, and you pick which of four countries each one was taken in. After every answer you see the exact place and a short description of the photograph.",
        features=["Five photographs a day from ten countries", "The exact place and a caption after each answer", "Photographs by Ben Ampel"],
        steps=[("Look at the photograph", "Take in the architecture, landscape, signs and light."),
               ("Choose a country", "Pick one of four countries."),
               ("Read the reveal", "You see the exact place, a short description and a link to more photographs from there."),
               ("Finish all five", "Your score and a shareable result appear after the fifth photograph.")],
        tips=["Look for architecture, vegetation and the quality of the light before you guess.",
              "Mountains with alpine meadows point toward Switzerland, black volcanic sand and waterfalls toward Iceland, and torii gates toward Japan.",
              "If two options both seem plausible, the one with more distinctive landmarks in the frame is usually right."],
        related=["daily-five", "daily-chess", "linkle"], og_photo="dsc-3638"),
    "games/daily-chess/": dict(
        slug="daily-chess", name="Daily Chess", genre="Chess puzzle", minutes=3,
        title="Daily Chess Puzzle: a free Lichess puzzle every day",
        desc="A free daily chess tactics puzzle from the Lichess puzzle database, easier on Monday and harder through the week. Find the best moves. No account needed.",
        answer="Daily Chess is a free daily chess tactics puzzle drawn from the Lichess puzzle database. Find the best move, then the follow-up, to win material or deliver checkmate. Monday's puzzle is the easiest and Sunday's is the hardest.",
        features=["One tactics puzzle a day from the Lichess puzzle database (CC0)", "Difficulty rises from Monday to Sunday", "Hints, a streak and a percentile against other players"],
        steps=[("Study the position", "The side to move is shown at the bottom of the board. The last move played is highlighted."),
               ("Make your move", "Click the piece, then click the square you want it to go to. Legal moves are shown with a dot."),
               ("Keep going", "After a correct move the opponent replies and you play the next move until the puzzle is won."),
               ("Use a hint if you are stuck", "A hint points to the piece to move. Hints and wrong moves count as slips in your result.")],
        tips=["Check every forcing move first: checks, captures and direct threats.",
              "Ask what the opponent's last move left undefended or attacked.",
              "Look for the patterns that decide most puzzles: forks, pins, skewers, discovered attacks and back-rank mates.",
              "When a puzzle says mate in two, count the opponent's possible replies before you commit."],
        related=["sudoku", "daily-five", "linkle"], og_photo="dsc-7919"),
    "games/sudoku/": dict(
        slug="sudoku", name="Sudoku", genre="Logic puzzle", minutes=12,
        title="Daily Sudoku: a free puzzle that gets harder every week",
        desc="A new Sudoku every day with one solution. Each week is harder than the last across a ten-week season, from Beginner to Expert. Free, with notes and checking.",
        answer="Daily Sudoku is a free daily Sudoku with exactly one solution. Difficulty rises every week across a ten-week season, from Beginner in the first two weeks to Expert in the last two, and then a new season starts.",
        features=["Unique-solution puzzles", "Ten-week seasons that get harder every week", "Pencil notes, checking and an optional auto-check", "Best time per difficulty level"],
        steps=[("Select a square", "Click it, or use the arrow keys to move around the grid."),
               ("Enter a digit", "Type 1 to 9 or use the number pad. Every row, column and 3 by 3 box must contain each digit once."),
               ("Use notes for candidates", "Turn on Notes to pencil small digits into a square without committing to them."),
               ("Check your work", "Duplicates turn red automatically. Check can test one square or the whole grid, and Auto-check flags wrong digits as you type.")],
        tips=["Start by scanning each digit: look for the one square in a row, column or box where that digit can go.",
              "Pencil notes pay off in the later weeks. Mark candidates, then look for pairs that share two candidates in a unit.",
              "When stuck, pick the row, column or box with the most digits already placed.",
              "From Hard onward, look for X-Wing patterns: a digit that appears in only two squares in each of two rows, in the same two columns."],
        related=["crossword", "linkle", "daily-chess"], og_photo="dsc-6626-edit"),
    "games/crossword/": dict(
        slug="crossword", name="Daily Crossword", genre="Crossword puzzle", minutes=10,
        title="Daily Crossword: a free themeless puzzle, easy Monday to hard Sunday",
        desc="A new free crossword every day, easiest on Monday and hardest on Sunday, with letter, word and puzzle checking. No account needed and no third-party ads.",
        answer="Daily Crossword is a free daily themeless crossword puzzle. The grid grows and the clues get trickier from Monday to Sunday, and you can check one letter, one word or the whole puzzle, or turn on auto-check.",
        features=["Grids from 9 by 9 on Monday to 15 by 15 on Sunday", "Check a letter, a word or the puzzle, plus auto-check", "Reveal a letter, a word or the puzzle", "Best time per weekday for unaided solves"],
        steps=[("Select a clue or a square", "Click a square and type. Click it again, or press Space, to switch between across and down."),
               ("Fill in the answers", "Arrow keys move around the grid, Tab jumps to the next clue and Backspace deletes."),
               ("Check as you go", "Check a letter, a word or the whole puzzle, or turn on auto-check to flag wrong letters as you type."),
               ("Finish the grid", "When every square is right you see your time, streak and best time for that weekday.")],
        tips=["Fill in the short answers you are sure of first, since they give you crossing letters for the long ones.",
              "Plurals usually end in S, and past-tense clues usually end in ED. The clue matches the answer's tense and number.",
              "A question mark at the end of a clue means light wordplay.",
              "On a phone, tap a square and use the on-screen keyboard. Tap the same square again to switch direction."],
        related=["sudoku", "linkle", "daily-five"], og_photo="dsc-4267"),
    "games/daily-stars/": dict(
        slug="daily-stars", name="Daily Stars", genre="Horoscope", minutes=1,
        title="Daily Stars: a short daily horoscope for every sign",
        desc="A short, plain daily reading for each of the twelve zodiac signs, written for entertainment. Free, new every day, and no account needed.",
        answer="Daily Stars is a free daily horoscope with a short reading for each of the twelve zodiac signs. The readings are written for entertainment and are not advice. A new set appears at midnight.",
        features=["A reading for each of the twelve signs", "The day's approximate moon phase", "Written for entertainment only"],
        steps=[("Choose your sign", "Pick your zodiac sign from the grid. The date ranges are shown on each button."),
               ("Read today's entry", "Each reading is two short sentences: a note on the day and a nudge for your sign."),
               ("Check the other signs", "Open any other sign from the list at the bottom of the page.")],
        tips=["Treat the readings as a prompt for the day, not a prediction.",
              "Your chosen sign is remembered in this browser, or on your account if you sign in."],
        related=["daily-photo", "daily-five", "linkle"], og_photo="dsc-8053"),
}

HUB = dict(
    title="Free daily games: Linkle, Sudoku, crossword, chess and more",
    desc="Free daily puzzles from Purplelink: a word game, a four-board word game, trivia, photo geography, chess, Sudoku, a crossword and a horoscope. New every midnight.",
    answer="Purplelink's daily games are a set of free puzzles that change every day at midnight: Linkle, Quadlink, Daily Five trivia, Daily Photo, Daily Chess, Sudoku, a themeless crossword and Daily Stars. You can play without an account, and there are no third-party ads.",
    og_photo="dsc-3940",
)
