"""Keep a YouTube broadcast bound to the stream key, so the radio never sits on air-but-unlisted.

stream.py ends the broadcast every 11 hours (YouTube only archives broadcasts under 12 hours) by
going silent for a few minutes, and used to rely on YouTube to open the next broadcast by itself when
the encoder came back. On 2026-10-06 it did not: the key reported `active` and `good` for hours while
the channel had no live video. This module creates the next broadcast through the Live API instead,
cloning the playback settings (DVR, latency, auto-start/stop) from the newest finished one. The title, description
and tags are written here, for search and for AI answers: see title_for, description_for and TAGS.

It needs a token for the channel that owns the stream, with the `youtube.force-ssl` scope, passed as
the JSON text of an authorized-user file in YT_LIVE_TOKEN_JSON (put it in stream.env next to
STREAM_URL; both are secrets). Without it the keeper logs once and does nothing, and the stream runs
exactly as before.

Checks run right after a broadcast starts, again 2 and 10 minutes later, then every hour: the broadcast
that was live can take a moment to close, and YouTube can end one on its own.
"""
from __future__ import annotations

import datetime
import json
import os
import threading
from typing import Callable

CHECKS_AFTER_START = (0, 120, 600)          # seconds; then every `hourly` seconds
STILL_OPEN = {"created", "ready", "testing", "liveStarting", "live"}

SITE = "https://purplelink.llc/?utm_source=youtube&utm_medium=stream&utm_campaign=chiptune-radio"

ERA_LABEL = {"16bit": "16-Bit", "8bit": "8-Bit", "synth": "Synthwave Chiptune", "hybrid": "Chiptune", None: "Chiptune"}
ERA_BLURB = {
    "16bit": "This broadcast is in a 16-bit console style: warm electric piano, flute, strings and soft pads.",
    "8bit": "This broadcast is in an 8-bit console style: pulse-wave melodies and a triangle bass.",
    "synth": "This broadcast is in a synthwave chiptune style: saw leads, plucks and warm pads.",
    "hybrid": "This broadcast mixes 8-bit, 16-bit and synth sounds.",
    None: "This broadcast mixes 8-bit, 16-bit and synth sounds.",
}

# Under YouTube's 500-character limit for the whole tag list (checked in test_broadcast.py).
TAGS = [
    "study music", "24/7 study music", "lofi study music", "chiptune", "chiptune study music", "8-bit music", "8bit lofi",
    "lofi", "lofi chiptune", "pomodoro timer", "pomodoro study", "pomodoro 25 5", "focus music", "concentration music",
    "deep work music", "coding music", "programming music", "writing music", "reading music", "study with me",
    "background music for studying", "video game music", "boss fight music", "pixel art", "no vocals", "instrumental",
    "live radio", "24/7 live stream",
]


def title_for(era: str | None) -> str:
    """Keywords first (study music, lofi chiptune, focus radio, pomodoro timer); the era makes each replay's title honest."""
    return f"24/7 {ERA_LABEL.get(era, ERA_LABEL[None])} Study Music | Lofi Chiptune Focus Radio with Pomodoro Timer (25/5)"[:100]


def description_for(era: str | None) -> str:
    """Written to be quoted: the first two lines carry the pitch and the ask, then plain question-and-answer blocks that a
    search result or an AI assistant can lift whole. Nothing here claims more than the stream does."""
    return f"""24/7 chiptune study music: calm lofi beats that slowly build into energetic boss-fight themes, with a built-in Pomodoro timer (25 minutes focus, 5 minutes break). Instrumental, no vocals.
👍 Like  🔔 Subscribe  🔁 Share with someone who is studying. It is what keeps this radio on the air.

WHAT IS THIS STREAM?
A free, always-on study radio. Original chiptune music plays over a pixel-art study room with a cat, a window that cycles from day to night, and a focus timer. {ERA_BLURB.get(era, ERA_BLURB[None])}

WHAT KIND OF MUSIC IS IT?
Chiptune: the sound of classic video game consoles, played gently. Over about two hours the music drifts slowly from soft, slow lofi (around 62 BPM) up to driving boss-fight energy (around 94 BPM) and back down, so a long session does not sound the same all the way through. Every track is generated by an algorithm as it plays, so the music is original and there are no copyrighted samples.

HOW DOES THE POMODORO TIMER WORK?
The timer on screen runs 25 minutes of focus followed by 5 minutes of break, repeating all day. A focus block starts at :00 and :30 past every hour (UTC). When it says FOCUS, work. When it says BREAK, stand up, stretch, drink some water.

WHO IS IT FOR?
Studying, coding, writing, reading, exam prep, homework and deep work. Keep it in the background, in a browser tab or on a second screen.

WHO MAKES IT?
Purplelink, which builds Mac apps and tools for researchers and students: {SITE}

#studymusic #lofi #chiptune #pomodoro #focusmusic #8bit #livestream"""


def tags_total() -> int:
    return sum(len(t) + (2 if " " in t else 0) for t in TAGS) + max(0, len(TAGS) - 1)


def configured() -> bool:
    return bool(os.environ.get("YT_LIVE_TOKEN_JSON"))


def _service():
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from googleapiclient.discovery import build
    creds = Credentials.from_authorized_user_info(json.loads(os.environ["YT_LIVE_TOKEN_JSON"]))
    if not creds.valid:
        creds.refresh(Request())
    return build("youtube", "v3", credentials=creds, cache_discovery=False)


def _norm(text: str) -> str:
    return "\n".join(line.rstrip() for line in (text or "").replace("\r\n", "\n").strip().splitlines())


def refresh_metadata(yt, video_id: str, era: str | None, log: Callable[[str], None] = print) -> str:
    """Bring an open broadcast's title, description and tags in line with the current ones (a restart reconnects to the
    broadcast that is already live, so a change here would otherwise wait for the next 11-hour rotation).
    Only writes when something differs, so the hourly check costs one cheap read."""
    try:
        items = yt.videos().list(part="snippet", id=video_id).execute().get("items", [])
        if not items:
            return "not readable yet"
        cur = items[0]["snippet"]
        want = {"title": title_for(era), "description": description_for(era), "tags": TAGS}
        same = (cur.get("title") == want["title"] and _norm(cur.get("description")) == _norm(want["description"])
                and set(cur.get("tags", [])) == set(want["tags"]))      # YouTube returns tags in its own order
        if same:
            return "current"
        yt.videos().update(part="snippet", body={"id": video_id, "snippet": {
            **want, "categoryId": cur.get("categoryId") or "10", "defaultLanguage": "en"}}).execute()
        return "refreshed"
    except Exception as e:  # noqa: BLE001 - cosmetic; never let it break the stream
        log(f"broadcast {video_id}: metadata refresh failed ({type(e).__name__})")
        return "refresh failed"


def ensure(era: str | None, yt=None, log: Callable[[str], None] = print) -> str:
    """Make sure one broadcast is open on the stream key. Returns what it did."""
    yt = yt or _service()
    items = yt.liveBroadcasts().list(part="snippet,contentDetails,status", mine=True,
                                     maxResults=25).execute().get("items", [])
    open_now = [b for b in items if b["status"]["lifeCycleStatus"] in STILL_OPEN]
    if open_now:
        b = open_now[0]
        return f"already open: {b['id']} ({b['status']['lifeCycleStatus']}), metadata {refresh_metadata(yt, b['id'], era, log)}"

    finished = [b for b in items if b["status"]["lifeCycleStatus"] == "complete"]
    tmpl = finished[0] if finished else (items[0] if items else None)
    stream_id = (tmpl or {}).get("contentDetails", {}).get("boundStreamId")
    if not stream_id:
        streams = yt.liveStreams().list(part="id", mine=True, maxResults=1).execute().get("items", [])
        if not streams:
            return "no stream key on the channel — nothing to bind to"
        stream_id = streams[0]["id"]

    cd = (tmpl or {}).get("contentDetails", {})
    start = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")
    created = yt.liveBroadcasts().insert(part="snippet,status,contentDetails", body={
        "snippet": {"title": title_for(era), "description": description_for(era), "scheduledStartTime": start},
        "status": {"privacyStatus": "public", "selfDeclaredMadeForKids": False},
        "contentDetails": {
            "enableAutoStart": True, "enableAutoStop": True,
            "enableDvr": cd.get("enableDvr", True), "recordFromStart": cd.get("recordFromStart", True),
            "enableEmbed": cd.get("enableEmbed", True),
            "latencyPreference": cd.get("latencyPreference", "low"),
            "enableClosedCaptions": False,
            "monitorStream": {"enableMonitorStream": True},
        }}).execute()
    yt.liveBroadcasts().bind(id=created["id"], part="id,contentDetails", streamId=stream_id).execute()

    # The broadcast's video starts with no category, tags or language. File it under Music and add the tags.
    # Search metadata is worth having but must never undo or hide the broadcast that now exists.
    try:
        yt.videos().update(part="snippet", body={"id": created["id"], "snippet": {
            "title": title_for(era), "description": description_for(era), "categoryId": "10",
            "tags": TAGS, "defaultLanguage": "en"}}).execute()
    except Exception as e:  # noqa: BLE001
        log(f"broadcast {created['id']}: tags and category not set ({type(e).__name__})")
    return f"created {created['id']} \"{title_for(era)}\""


def keep(era: str | None, cancel: threading.Event, log: Callable[[str], None] = print,
         hourly: float = 3600.0, ensure_fn=ensure) -> None:
    """Run in a thread for the lifetime of one broadcast; `cancel` ends it."""
    waits = [CHECKS_AFTER_START[0]] + [b - a for a, b in zip(CHECKS_AFTER_START, CHECKS_AFTER_START[1:])]
    i = 0
    while not cancel.is_set():
        wait = waits[i] if i < len(waits) else hourly
        i += 1
        if cancel.wait(wait):
            return
        try:
            log(f"broadcast check: {ensure_fn(era)}")
        except Exception as e:  # noqa: BLE001 - the stream must keep running whatever YouTube says
            log(f"broadcast check failed: {type(e).__name__}: {str(e)[:160]}")
